name: readme-updater

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/**'
  workflow_dispatch:

jobs:
  run_generator:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Check working directory
        run: |
          pwd
          ls
      - name: Run generator
        run: python scripts/readme_generator.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update README
          file_pattern: README.md
          commit_options: '--signoff'
          push_options: '--force'